[[plugins]]
package = "netlify-plugin-nimbella"

[plugins.inputs]
path    = "/api"   # The prefix path to access your deployed packages.
web     = false    # Deploy frontend and proxy domain to Nimbella (allowed values are true or false).
env     = []       # Environment variables to export to serverless APIs.

[build]
  base = "."
  publish = "public"
  command = "# no build step"

[nimbella]
  # Base path that you want to use to access functions. Example https://your-site.com/api/default/greet
  path = "/api/"
